# A workflow runs all tests and creates/updates Docker image
name: Run tests and update image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '21'

      - name: Run all tests in project
        run: |
           mvn compile && mvn test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish updated image
        run: |
          mvn package
          reponame_lowercase=${GITHUB_REPOSITORY,,}
          image_name=$(echo ${reponame_lowercase} | cut -f2 -d/)-img
          image_tag=ghcr.io/${reponame_lowercase}/${image_name}:latest
          echo "Image tag is ${image_tag}"
          docker build . --tag ${image_tag}
          docker push ${image_tag}

      - name: Download latest test coverage report
        uses: actions/download-artifact@v3
        with:
          name: test-coverage-report
          path: coverage

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './coverage/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
